/**
 * GENERATED FILE — do not edit by hand.
 *
 * Regenerate with:
 *   uv run --directory pipeline python scripts/generate_country_registry.py
 *
 * Source: Natural Earth ne_50m_admin_0_countries — the same admin-0 layer the pipeline
 * builds the tiles' `country` level from, with the same `-99` sentinel
 * blanking. Every ISO-2 code a painted polygon can carry appears here, so
 * the map's click handler resolves a name and a slug for all of them.
 *
 * Territories Natural Earth files under a parent's code (Ashmore and
 * Cartier Islands under `AU`) collapse onto the parent, which is what the
 * map should navigate to. Polygons with no ISO-2 at all (Somaliland,
 * Northern Cyprus, the Siachen Glacier) are absent: they are painted but
 * non-routable, exactly as the pipeline leaves them.
 */

import type { CountryRef } from "./countries";

export const GENERATED_COUNTRIES: readonly CountryRef[] = [
  { slug: "afghanistan", name: "Afghanistan", iso2: "AF", region: "Asia" },
  { slug: "albania", name: "Albania", iso2: "AL", region: "Europe" },
  { slug: "algeria", name: "Algeria", iso2: "DZ", region: "Africa" },
  { slug: "american-samoa", name: "American Samoa", iso2: "AS", region: "Oceania" },
  { slug: "andorra", name: "Andorra", iso2: "AD", region: "Europe" },
  { slug: "angola", name: "Angola", iso2: "AO", region: "Africa" },
  { slug: "anguilla", name: "Anguilla", iso2: "AI", region: "North America" },
  { slug: "antarctica", name: "Antarctica", iso2: "AQ", region: "Antarctica" },
  { slug: "antigua-and-barbuda", name: "Antigua and Barbuda", iso2: "AG", region: "North America" },
  { slug: "argentina", name: "Argentina", iso2: "AR", region: "South America" },
  { slug: "armenia", name: "Armenia", iso2: "AM", region: "Asia" },
  { slug: "aruba", name: "Aruba", iso2: "AW", region: "North America" },
  { slug: "australia", name: "Australia", iso2: "AU", region: "Oceania" },
  { slug: "austria", name: "Austria", iso2: "AT", region: "Europe" },
  { slug: "azerbaijan", name: "Azerbaijan", iso2: "AZ", region: "Asia" },
  { slug: "bahrain", name: "Bahrain", iso2: "BH", region: "Asia" },
  { slug: "bangladesh", name: "Bangladesh", iso2: "BD", region: "Asia" },
  { slug: "barbados", name: "Barbados", iso2: "BB", region: "North America" },
  { slug: "belarus", name: "Belarus", iso2: "BY", region: "Europe" },
  { slug: "belgium", name: "Belgium", iso2: "BE", region: "Europe" },
  { slug: "belize", name: "Belize", iso2: "BZ", region: "North America" },
  { slug: "benin", name: "Benin", iso2: "BJ", region: "Africa" },
  { slug: "bermuda", name: "Bermuda", iso2: "BM", region: "North America" },
  { slug: "bhutan", name: "Bhutan", iso2: "BT", region: "Asia" },
  { slug: "bolivia", name: "Bolivia", iso2: "BO", region: "South America" },
  { slug: "bosnia-and-herzegovina", name: "Bosnia and Herzegovina", iso2: "BA", region: "Europe" },
  { slug: "botswana", name: "Botswana", iso2: "BW", region: "Africa" },
  { slug: "brazil", name: "Brazil", iso2: "BR", region: "South America" },
  { slug: "british-indian-ocean-territory", name: "British Indian Ocean Territory", iso2: "IO", region: "Africa" },
  { slug: "british-virgin-islands", name: "British Virgin Islands", iso2: "VG", region: "North America" },
  { slug: "brunei", name: "Brunei", iso2: "BN", region: "Asia" },
  { slug: "bulgaria", name: "Bulgaria", iso2: "BG", region: "Europe" },
  { slug: "burkina-faso", name: "Burkina Faso", iso2: "BF", region: "Africa" },
  { slug: "burundi", name: "Burundi", iso2: "BI", region: "Africa" },
  { slug: "cambodia", name: "Cambodia", iso2: "KH", region: "Asia" },
  { slug: "cameroon", name: "Cameroon", iso2: "CM", region: "Africa" },
  { slug: "canada", name: "Canada", iso2: "CA", region: "North America" },
  { slug: "cape-verde", name: "Cape Verde", iso2: "CV", region: "Africa" },
  { slug: "cayman-islands", name: "Cayman Islands", iso2: "KY", region: "North America" },
  { slug: "central-african-republic", name: "Central African Republic", iso2: "CF", region: "Africa" },
  { slug: "chad", name: "Chad", iso2: "TD", region: "Africa" },
  { slug: "chile", name: "Chile", iso2: "CL", region: "South America" },
  { slug: "china", name: "China", iso2: "CN", region: "Asia" },
  { slug: "colombia", name: "Colombia", iso2: "CO", region: "South America" },
  { slug: "comoros", name: "Comoros", iso2: "KM", region: "Africa" },
  { slug: "cook-islands", name: "Cook Islands", iso2: "CK", region: "Oceania" },
  { slug: "costa-rica", name: "Costa Rica", iso2: "CR", region: "North America" },
  { slug: "croatia", name: "Croatia", iso2: "HR", region: "Europe" },
  { slug: "cuba", name: "Cuba", iso2: "CU", region: "North America" },
  { slug: "curacao", name: "Curaçao", iso2: "CW", region: "North America" },
  { slug: "cyprus", name: "Cyprus", iso2: "CY", region: "Asia" },
  { slug: "czech-republic", name: "Czech Republic", iso2: "CZ", region: "Europe" },
  { slug: "democratic-republic-of-the-congo", name: "Democratic Republic of the Congo", iso2: "CD", region: "Africa" },
  { slug: "denmark", name: "Denmark", iso2: "DK", region: "Europe" },
  { slug: "djibouti", name: "Djibouti", iso2: "DJ", region: "Africa" },
  { slug: "dominica", name: "Dominica", iso2: "DM", region: "North America" },
  { slug: "dominican-republic", name: "Dominican Republic", iso2: "DO", region: "North America" },
  { slug: "east-timor", name: "East Timor", iso2: "TL", region: "Asia" },
  { slug: "ecuador", name: "Ecuador", iso2: "EC", region: "South America" },
  { slug: "egypt", name: "Egypt", iso2: "EG", region: "Africa" },
  { slug: "el-salvador", name: "El Salvador", iso2: "SV", region: "North America" },
  { slug: "equatorial-guinea", name: "Equatorial Guinea", iso2: "GQ", region: "Africa" },
  { slug: "eritrea", name: "Eritrea", iso2: "ER", region: "Africa" },
  { slug: "estonia", name: "Estonia", iso2: "EE", region: "Europe" },
  { slug: "eswatini", name: "Eswatini", iso2: "SZ", region: "Africa" },
  { slug: "ethiopia", name: "Ethiopia", iso2: "ET", region: "Africa" },
  { slug: "falkland-islands", name: "Falkland Islands", iso2: "FK", region: "South America" },
  { slug: "faroe-islands", name: "Faroe Islands", iso2: "FO", region: "Europe" },
  { slug: "federated-states-of-micronesia", name: "Federated States of Micronesia", iso2: "FM", region: "Oceania" },
  { slug: "fiji", name: "Fiji", iso2: "FJ", region: "Oceania" },
  { slug: "finland", name: "Finland", iso2: "FI", region: "Europe" },
  { slug: "france", name: "France", iso2: "FR", region: "Europe" },
  { slug: "french-polynesia", name: "French Polynesia", iso2: "PF", region: "Oceania" },
  { slug: "french-southern-and-antarctic-lands", name: "French Southern and Antarctic Lands", iso2: "TF", region: "Africa" },
  { slug: "gabon", name: "Gabon", iso2: "GA", region: "Africa" },
  { slug: "georgia", name: "Georgia", iso2: "GE", region: "Asia" },
  { slug: "germany", name: "Germany", iso2: "DE", region: "Europe" },
  { slug: "ghana", name: "Ghana", iso2: "GH", region: "Africa" },
  { slug: "greece", name: "Greece", iso2: "GR", region: "Europe" },
  { slug: "greenland", name: "Greenland", iso2: "GL", region: "North America" },
  { slug: "grenada", name: "Grenada", iso2: "GD", region: "North America" },
  { slug: "guam", name: "Guam", iso2: "GU", region: "Oceania" },
  { slug: "guatemala", name: "Guatemala", iso2: "GT", region: "North America" },
  { slug: "guernsey", name: "Guernsey", iso2: "GG", region: "Europe" },
  { slug: "guinea", name: "Guinea", iso2: "GN", region: "Africa" },
  { slug: "guinea-bissau", name: "Guinea-Bissau", iso2: "GW", region: "Africa" },
  { slug: "guyana", name: "Guyana", iso2: "GY", region: "South America" },
  { slug: "haiti", name: "Haiti", iso2: "HT", region: "North America" },
  { slug: "heard-island-and-mcdonald-islands", name: "Heard Island and McDonald Islands", iso2: "HM", region: "Africa" },
  { slug: "honduras", name: "Honduras", iso2: "HN", region: "North America" },
  { slug: "hong-kong", name: "Hong Kong", iso2: "HK", region: "Asia" },
  { slug: "hungary", name: "Hungary", iso2: "HU", region: "Europe" },
  { slug: "iceland", name: "Iceland", iso2: "IS", region: "Europe" },
  { slug: "india", name: "India", iso2: "IN", region: "Asia" },
  { slug: "indonesia", name: "Indonesia", iso2: "ID", region: "Asia" },
  { slug: "iran", name: "Iran", iso2: "IR", region: "Asia" },
  { slug: "iraq", name: "Iraq", iso2: "IQ", region: "Asia" },
  { slug: "ireland", name: "Ireland", iso2: "IE", region: "Europe" },
  { slug: "isle-of-man", name: "Isle of Man", iso2: "IM", region: "Europe" },
  { slug: "israel", name: "Israel", iso2: "IL", region: "Asia" },
  { slug: "italy", name: "Italy", iso2: "IT", region: "Europe" },
  { slug: "ivory-coast", name: "Ivory Coast", iso2: "CI", region: "Africa" },
  { slug: "jamaica", name: "Jamaica", iso2: "JM", region: "North America" },
  { slug: "japan", name: "Japan", iso2: "JP", region: "Asia" },
  { slug: "jersey", name: "Jersey", iso2: "JE", region: "Europe" },
  { slug: "jordan", name: "Jordan", iso2: "JO", region: "Asia" },
  { slug: "kazakhstan", name: "Kazakhstan", iso2: "KZ", region: "Asia" },
  { slug: "kenya", name: "Kenya", iso2: "KE", region: "Africa" },
  { slug: "kiribati", name: "Kiribati", iso2: "KI", region: "Oceania" },
  { slug: "kosovo", name: "Kosovo", iso2: "XK", region: "Europe" },
  { slug: "kuwait", name: "Kuwait", iso2: "KW", region: "Asia" },
  { slug: "kyrgyzstan", name: "Kyrgyzstan", iso2: "KG", region: "Asia" },
  { slug: "laos", name: "Laos", iso2: "LA", region: "Asia" },
  { slug: "latvia", name: "Latvia", iso2: "LV", region: "Europe" },
  { slug: "lebanon", name: "Lebanon", iso2: "LB", region: "Asia" },
  { slug: "lesotho", name: "Lesotho", iso2: "LS", region: "Africa" },
  { slug: "liberia", name: "Liberia", iso2: "LR", region: "Africa" },
  { slug: "libya", name: "Libya", iso2: "LY", region: "Africa" },
  { slug: "liechtenstein", name: "Liechtenstein", iso2: "LI", region: "Europe" },
  { slug: "lithuania", name: "Lithuania", iso2: "LT", region: "Europe" },
  { slug: "luxembourg", name: "Luxembourg", iso2: "LU", region: "Europe" },
  { slug: "macau", name: "Macau", iso2: "MO", region: "Asia" },
  { slug: "madagascar", name: "Madagascar", iso2: "MG", region: "Africa" },
  { slug: "malawi", name: "Malawi", iso2: "MW", region: "Africa" },
  { slug: "malaysia", name: "Malaysia", iso2: "MY", region: "Asia" },
  { slug: "maldives", name: "Maldives", iso2: "MV", region: "Asia" },
  { slug: "mali", name: "Mali", iso2: "ML", region: "Africa" },
  { slug: "malta", name: "Malta", iso2: "MT", region: "Europe" },
  { slug: "marshall-islands", name: "Marshall Islands", iso2: "MH", region: "Oceania" },
  { slug: "mauritania", name: "Mauritania", iso2: "MR", region: "Africa" },
  { slug: "mauritius", name: "Mauritius", iso2: "MU", region: "Africa" },
  { slug: "mexico", name: "Mexico", iso2: "MX", region: "North America" },
  { slug: "moldova", name: "Moldova", iso2: "MD", region: "Europe" },
  { slug: "monaco", name: "Monaco", iso2: "MC", region: "Europe" },
  { slug: "mongolia", name: "Mongolia", iso2: "MN", region: "Asia" },
  { slug: "montenegro", name: "Montenegro", iso2: "ME", region: "Europe" },
  { slug: "montserrat", name: "Montserrat", iso2: "MS", region: "North America" },
  { slug: "morocco", name: "Morocco", iso2: "MA", region: "Africa" },
  { slug: "mozambique", name: "Mozambique", iso2: "MZ", region: "Africa" },
  { slug: "myanmar", name: "Myanmar", iso2: "MM", region: "Asia" },
  { slug: "namibia", name: "Namibia", iso2: "NA", region: "Africa" },
  { slug: "nauru", name: "Nauru", iso2: "NR", region: "Oceania" },
  { slug: "nepal", name: "Nepal", iso2: "NP", region: "Asia" },
  { slug: "netherlands", name: "Netherlands", iso2: "NL", region: "Europe" },
  { slug: "new-caledonia", name: "New Caledonia", iso2: "NC", region: "Oceania" },
  { slug: "new-zealand", name: "New Zealand", iso2: "NZ", region: "Oceania" },
  { slug: "nicaragua", name: "Nicaragua", iso2: "NI", region: "North America" },
  { slug: "niger", name: "Niger", iso2: "NE", region: "Africa" },
  { slug: "nigeria", name: "Nigeria", iso2: "NG", region: "Africa" },
  { slug: "niue", name: "Niue", iso2: "NU", region: "Oceania" },
  { slug: "norfolk-island", name: "Norfolk Island", iso2: "NF", region: "Oceania" },
  { slug: "north-korea", name: "North Korea", iso2: "KP", region: "Asia" },
  { slug: "north-macedonia", name: "North Macedonia", iso2: "MK", region: "Europe" },
  { slug: "northern-mariana-islands", name: "Northern Mariana Islands", iso2: "MP", region: "Oceania" },
  { slug: "norway", name: "Norway", iso2: "NO", region: "Europe" },
  { slug: "oman", name: "Oman", iso2: "OM", region: "Asia" },
  { slug: "pakistan", name: "Pakistan", iso2: "PK", region: "Asia" },
  { slug: "palau", name: "Palau", iso2: "PW", region: "Oceania" },
  { slug: "palestine", name: "Palestine", iso2: "PS", region: "Asia" },
  { slug: "panama", name: "Panama", iso2: "PA", region: "North America" },
  { slug: "papua-new-guinea", name: "Papua New Guinea", iso2: "PG", region: "Oceania" },
  { slug: "paraguay", name: "Paraguay", iso2: "PY", region: "South America" },
  { slug: "peru", name: "Peru", iso2: "PE", region: "South America" },
  { slug: "philippines", name: "Philippines", iso2: "PH", region: "Asia" },
  { slug: "pitcairn-islands", name: "Pitcairn Islands", iso2: "PN", region: "Oceania" },
  { slug: "poland", name: "Poland", iso2: "PL", region: "Europe" },
  { slug: "portugal", name: "Portugal", iso2: "PT", region: "Europe" },
  { slug: "puerto-rico", name: "Puerto Rico", iso2: "PR", region: "North America" },
  { slug: "qatar", name: "Qatar", iso2: "QA", region: "Asia" },
  { slug: "republic-of-the-congo", name: "Republic of the Congo", iso2: "CG", region: "Africa" },
  { slug: "romania", name: "Romania", iso2: "RO", region: "Europe" },
  { slug: "russia", name: "Russia", iso2: "RU", region: "Europe" },
  { slug: "rwanda", name: "Rwanda", iso2: "RW", region: "Africa" },
  { slug: "saint-barthelemy", name: "Saint Barthélemy", iso2: "BL", region: "North America" },
  { slug: "saint-helena", name: "Saint Helena", iso2: "SH", region: "Africa" },
  { slug: "saint-kitts-and-nevis", name: "Saint Kitts and Nevis", iso2: "KN", region: "North America" },
  { slug: "saint-lucia", name: "Saint Lucia", iso2: "LC", region: "North America" },
  { slug: "saint-martin", name: "Saint Martin", iso2: "MF", region: "North America" },
  { slug: "saint-pierre-and-miquelon", name: "Saint Pierre and Miquelon", iso2: "PM", region: "North America" },
  { slug: "saint-vincent-and-the-grenadines", name: "Saint Vincent and the Grenadines", iso2: "VC", region: "North America" },
  { slug: "samoa", name: "Samoa", iso2: "WS", region: "Oceania" },
  { slug: "san-marino", name: "San Marino", iso2: "SM", region: "Europe" },
  { slug: "saudi-arabia", name: "Saudi Arabia", iso2: "SA", region: "Asia" },
  { slug: "senegal", name: "Senegal", iso2: "SN", region: "Africa" },
  { slug: "serbia", name: "Serbia", iso2: "RS", region: "Europe" },
  { slug: "seychelles", name: "Seychelles", iso2: "SC", region: "Africa" },
  { slug: "sierra-leone", name: "Sierra Leone", iso2: "SL", region: "Africa" },
  { slug: "singapore", name: "Singapore", iso2: "SG", region: "Asia" },
  { slug: "sint-maarten", name: "Sint Maarten", iso2: "SX", region: "North America" },
  { slug: "slovakia", name: "Slovakia", iso2: "SK", region: "Europe" },
  { slug: "slovenia", name: "Slovenia", iso2: "SI", region: "Europe" },
  { slug: "solomon-islands", name: "Solomon Islands", iso2: "SB", region: "Oceania" },
  { slug: "somalia", name: "Somalia", iso2: "SO", region: "Africa" },
  { slug: "south-africa", name: "South Africa", iso2: "ZA", region: "Africa" },
  { slug: "south-georgia-and-the-south-sandwich-islands", name: "South Georgia and the South Sandwich Islands", iso2: "GS", region: "Americas" },
  { slug: "south-korea", name: "South Korea", iso2: "KR", region: "Asia" },
  { slug: "south-sudan", name: "South Sudan", iso2: "SS", region: "Africa" },
  { slug: "spain", name: "Spain", iso2: "ES", region: "Europe" },
  { slug: "sri-lanka", name: "Sri Lanka", iso2: "LK", region: "Asia" },
  { slug: "sudan", name: "Sudan", iso2: "SD", region: "Africa" },
  { slug: "suriname", name: "Suriname", iso2: "SR", region: "South America" },
  { slug: "sweden", name: "Sweden", iso2: "SE", region: "Europe" },
  { slug: "switzerland", name: "Switzerland", iso2: "CH", region: "Europe" },
  { slug: "syria", name: "Syria", iso2: "SY", region: "Asia" },
  { slug: "sao-tome-and-principe", name: "São Tomé and Príncipe", iso2: "ST", region: "Africa" },
  { slug: "taiwan", name: "Taiwan", iso2: "TW", region: "Asia" },
  { slug: "tajikistan", name: "Tajikistan", iso2: "TJ", region: "Asia" },
  { slug: "tanzania", name: "Tanzania", iso2: "TZ", region: "Africa" },
  { slug: "thailand", name: "Thailand", iso2: "TH", region: "Asia" },
  { slug: "the-bahamas", name: "The Bahamas", iso2: "BS", region: "North America" },
  { slug: "the-gambia", name: "The Gambia", iso2: "GM", region: "Africa" },
  { slug: "togo", name: "Togo", iso2: "TG", region: "Africa" },
  { slug: "tonga", name: "Tonga", iso2: "TO", region: "Oceania" },
  { slug: "trinidad-and-tobago", name: "Trinidad and Tobago", iso2: "TT", region: "North America" },
  { slug: "tunisia", name: "Tunisia", iso2: "TN", region: "Africa" },
  { slug: "turkey", name: "Turkey", iso2: "TR", region: "Asia" },
  { slug: "turkmenistan", name: "Turkmenistan", iso2: "TM", region: "Asia" },
  { slug: "turks-and-caicos-islands", name: "Turks and Caicos Islands", iso2: "TC", region: "North America" },
  { slug: "tuvalu", name: "Tuvalu", iso2: "TV", region: "Oceania" },
  { slug: "uganda", name: "Uganda", iso2: "UG", region: "Africa" },
  { slug: "ukraine", name: "Ukraine", iso2: "UA", region: "Europe" },
  { slug: "united-arab-emirates", name: "United Arab Emirates", iso2: "AE", region: "Asia" },
  { slug: "united-kingdom", name: "United Kingdom", iso2: "GB", region: "Europe" },
  { slug: "united-states", name: "United States", iso2: "US", region: "North America" },
  { slug: "united-states-virgin-islands", name: "United States Virgin Islands", iso2: "VI", region: "North America" },
  { slug: "uruguay", name: "Uruguay", iso2: "UY", region: "South America" },
  { slug: "uzbekistan", name: "Uzbekistan", iso2: "UZ", region: "Asia" },
  { slug: "vanuatu", name: "Vanuatu", iso2: "VU", region: "Oceania" },
  { slug: "vatican-city", name: "Vatican City", iso2: "VA", region: "Europe" },
  { slug: "venezuela", name: "Venezuela", iso2: "VE", region: "South America" },
  { slug: "vietnam", name: "Vietnam", iso2: "VN", region: "Asia" },
  { slug: "wallis-and-futuna", name: "Wallis and Futuna", iso2: "WF", region: "Oceania" },
  { slug: "western-sahara", name: "Western Sahara", iso2: "EH", region: "Africa" },
  { slug: "yemen", name: "Yemen", iso2: "YE", region: "Asia" },
  { slug: "zambia", name: "Zambia", iso2: "ZM", region: "Africa" },
  { slug: "zimbabwe", name: "Zimbabwe", iso2: "ZW", region: "Africa" },
  { slug: "aland", name: "Åland", iso2: "AX", region: "Europe" },
];
