"""Read the pipeline's published country bundle.

``wtg publish api-data`` writes ``pipeline/data/final/api/`` — one JSON payload
per country plus an index — and ``docker-compose.yml`` mounts that directory
read-only at :data:`Settings.country_data_dir` (``/srv/wtg-data`` in the
container). This module is the only thing in the API that touches it.

Why a directory and not Postgres: the pipeline runs on the *host* while
Postgres is on an internal-only Docker network that ``infra/CLAUDE.md`` forbids
exposing, so a publish step that wrote rows would have to punch through that
rule first. The payloads are read-only reference data with no per-user state,
regenerated whole by a yearly climate rebuild and a weekly advisory run.

Caching
-------

Payloads are cached in-process, keyed by slug, and invalidated on the file's
mtime. That matters because a rebuild replaces the files underneath a running
container: ``rebuild-tiles.sh`` does not restart the API, and neither does the
weekly advisory cron. An mtime check is one ``stat`` per request against a
local bind mount — cheaper than the JSON parse it skips.
"""

from __future__ import annotations

import json
import logging
import re
import threading
from pathlib import Path
from typing import Any

from wtg_api.config import get_settings

log = logging.getLogger(__name__)

# Slugs are generated by `wtg_pipeline.processing.country_registry.slugify`,
# which emits nothing but `[a-z0-9-]`. Validating against that here is not
# belt-and-braces: the slug is interpolated into a filesystem path, and
# `../../etc/passwd` is a slug-shaped string right up until it isn't.
SLUG_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")

_LOCK = threading.Lock()
_CACHE: dict[str, tuple[float, Any]] = {}


class CountryDataUnavailable(RuntimeError):
    """The bundle directory is absent — the deploy is missing a mount."""


def data_dir() -> Path:
    return Path(get_settings().country_data_dir)


def index_path() -> Path:
    return data_dir() / "index.json"


def country_path(slug: str) -> Path:
    return data_dir() / "countries" / f"{slug}.json"


def reset_cache() -> None:
    """Drop the in-process cache. Used by tests that swap the data directory."""
    with _LOCK:
        _CACHE.clear()


def _load(path: Path) -> Any | None:
    """Parse ``path``, memoised on its mtime. ``None`` when it does not exist."""
    try:
        mtime = path.stat().st_mtime
    except OSError:
        with _LOCK:
            _CACHE.pop(str(path), None)
        return None

    key = str(path)
    with _LOCK:
        cached = _CACHE.get(key)
        if cached is not None and cached[0] == mtime:
            return cached[1]

    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        # A half-written file during a republish, or a corrupt payload. Treat
        # it as absent rather than 500 — one country page falls over, not the
        # whole route.
        log.exception("could not read published country data at %s", path)
        return None

    with _LOCK:
        _CACHE[key] = (mtime, payload)
    return payload


def load_index() -> list[dict[str, Any]]:
    """Every published country: slug, name, iso2, region.

    Raises :class:`CountryDataUnavailable` when the bundle is missing entirely.
    The web builds its whole static route tree off this list, so answering an
    empty list would silently ship a site with no country pages at all —
    louder is better.
    """
    payload = _load(index_path())
    if payload is None:
        raise CountryDataUnavailable(
            f"no published country data at {index_path()}. The API expects the "
            f"pipeline's `wtg publish api-data` output mounted read-only at "
            f"{data_dir()}."
        )
    countries = payload.get("countries") if isinstance(payload, dict) else None
    return countries if isinstance(countries, list) else []


def load_country(slug: str) -> dict[str, Any] | None:
    """One country payload, or ``None`` when the slug is not published."""
    normalised = slug.strip().lower()
    if not SLUG_RE.match(normalised):
        return None
    payload = _load(country_path(normalised))
    return payload if isinstance(payload, dict) else None


def find_region(country: dict[str, Any], region_slug: str) -> dict[str, Any] | None:
    """One admin-1 row out of a country payload, by its published slug."""
    wanted = region_slug.strip().lower()
    regions = country.get("regions")
    if not isinstance(regions, list):
        return None
    for region in regions:
        if isinstance(region, dict) and str(region.get("slug", "")) == wanted:
            return region
    return None
